-- Añadir todas las columnas de la migración add_event_steps_fields (por si faltan en la DB)
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3);
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "endTime" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "region" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "eventType" TEXT NOT NULL DEFAULT 'PUBLICO';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "eventMode" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "ageRestriction" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "minAge" INTEGER;
